### ISSUE TITLE
Logo Proposal 

### ISSUE THREAD

**Issue by Arslanshn** [mcao/RoBot#32]
Hi,Michael I want to design a new logo for the project completely free...

**Comment by mcao** [comment]
sure

**Comment by Arslanshn** [comment]
I did not understand your message. Do you want logo for the project?

**Comment by mcao** [comment]
yes, I would!

**Comment by Arslanshn** [comment]
https://drive.google.com/open?id=11NbbmJsKJqzFLSo3cqFR7TdroDdwEl3y
hello I did a study I hope you like:)

**Comment by Arslanshn** [comment]
Hi,Michael Can I learn the thought about the logo?

**Comment by mcao** [comment]
It's good but the second file is not in a format I can see. I'll be asking others if it's good soon.
